image: node:12.18.2-alpine3.12

pages:
    cache:
        paths:
        - node_modules/

    script:
    - npm ci
    - npm run build
    
    artifacts:
        paths:
        - dist
    
    only:
    - master
